#!/bin/bash
#SBATCH -c 18                               # Number of CPUS requested. If omitted, the default is 1 CPU.
#SBATCH --mem=400gb                         # mem in gb
#SBATCH -t 10-0:0:0                         # How long will your job run for? If omitted, the default is 3 hours.
#SBATCH -J anvio5_1.400                	# Name of job
#SBATCH -e /global/scratch/hpc3565/anvio5_v13_v10_4_summarize.err  
#SBATCH -o /global/scratch/hpc3565/anvio5_v13_v10_4_summarize.out


# processing back on CAC
source activate anvio5

# making environmental variables
R1s=`ls /global/scratch/hpc3565/coassembly/*1P*`
R2s=`ls /global/scratch/hpc3565/coassembly/*2P*`

BASEDIR=/global/scratch/hpc3565
#these contigs have only prokaryotic reads filtered by EukRep
OUTPUT=$BASEDIR/output_anvio5_1
#DNA=$HOME/rna_dna_2017/dna/raw_data/data_complete/output_anvio
#CONTIGS=$DNA/contigs.fa
CONTIGS=$BASEDIR/megahit_coassembly_v13/prokarya_all.fa
READS=$HOME/rna_dna_2017/dna/raw_data/data_complete
MAPPING=$OUTPUT/mapping
KAIJU=$HOME/rna_dna_2017/dna/raw_data/data_complete/kaiju/bin
KAIJUFILES=$HOME/rna_dna_2017/dna/raw_data/data_complete/kaijudb_prokaryotes

#local
BASEDIR=/Users/grahamcolby/Documents/anvio_refining
OUTPUT=/Users/grahamcolby/Documents/anvio_refining


#
cd $OUTPUT

anvi-show-collections-and-bins -p $OUTPUT/SAMPLES-MERGED/PROFILE.db
anvi-script-get-collection-info -c $OUTPUT/contigs.db -p $OUTPUT/SAMPLES-MERGED/PROFILE.db --list-collections  --output-file $OUTPUT/collections.txt
anvi-script-get-collection-info -c $OUTPUT/contigs.db -p $OUTPUT/SAMPLES-MERGED/PROFILE.db -C CONCOCT


anvi-refine -p MERGED_PROFILE/PROFILE.db -c contigs.db -C CONCOCT -b Group_6
anvi-refine -p $OUTPUT/SAMPLES-MERGED/PROFILE.db -c $OUTPUT/contigs_refined.db -C CONCOCT -b Bin_56

anvi-refine
