#!/bin/bash
#SBATCH -c 18                               # Number of CPUS requested. If omitted, the default is 1 CPU.
#SBATCH --mem=400gb                         # mem in gb
#SBATCH -t 10-0:0:0                         # How long will your job run for? If omitted, the default is 3 hours.
#SBATCH -J anvio5_1.400                	# Name of job
#SBATCH -e /global/scratch/hpc3565/anvio5_v13_v10_4_summarize.err  
#SBATCH -o /global/scratch/hpc3565/anvio5_v13_v10_4_summarize.out


# processing back on CAC
source activate anvio5.1.0

# making environmental variables
R1s=`ls /global/scratch/hpc3565/coassembly/*1P*`
R2s=`ls /global/scratch/hpc3565/coassembly/*2P*`

BASEDIR=/global/scratch/hpc3565
#these contigs have only prokaryotic reads filtered by EukRep
OUTPUT=$BASEDIR/output_anvio5_1
#DNA=$HOME/rna_dna_2017/dna/raw_data/data_complete/output_anvio
#CONTIGS=$DNA/contigs.fa
CONTIGS=$BASEDIR/megahit_coassembly_v13/prokarya_all.fa
READS=$HOME/rna_dna_2017/dna/raw_data/data_complete
MAPPING=$OUTPUT/mapping
KAIJU=$HOME/rna_dna_2017/dna/raw_data/data_complete/kaiju/bin
KAIJUFILES=$HOME/rna_dna_2017/dna/raw_data/data_complete/kaijudb_prokaryotes

#local
BASEDIR=/Users/grahamcolby/Documents/anvio_refining
OUTPUT=/Users/grahamcolby/Documents/anvio_refining
BACKUP=$OUTPUT/anvio_refining_backup

# Refining steps 
cd $OUTPUT

anvi-show-collections-and-bins -p $OUTPUT/SAMPLES-MERGED/PROFILE.db
anvi-show-collections-and-bins -p $OUTPUT/SAMPLES-MERGED-concoct/PROFILE.db
anvi-script-get-collection-info -c contigs.db -p SAMPLES-MERGED/PROFILE.db  -C CONCOCT --output-file collections-anvio-rerefined.txt

anvi-script-get-collection-info -c $OUTPUT/contigs.db -p $OUTPUT/SAMPLES-MERGED-rerun2/PROFILE.db --list-collections  --output-file $OUTPUT/collections.txt
anvi-script-get-collection-info -c $OUTPUT/contigs.db -p $OUTPUT/SAMPLES-MERGED/PROFILE.db -C CONCOCT --output-file $OUTPUT/collections_update.txt
anvi-summarize  --quick-summary
anvi-summarize -p $OUTPUT/SAMPLES-MERGED-rerun2/PROFILE.db -c $OUTPUT/contigs.db -C CONCOCT 


# Ensuring back-up are appropriately stored
##### essential
anvi-display-contigs-stats $OUTPUT/contigs.db --report-as-text -o $OUTPUT/contig_stats_anvio5_1.6.txt
anvi-db-info $OUTPUT/contigs.db
anvi-db-info $OUTPUT/HI.DNA_AS3/PROFILE.db
anvi-db-info $OUTPUT/HI.DNA_AS3/AUXILIARY-DATA.db
anvi-db-info $OUTPUT/SAMPLES-MERGED-rerun/PROFILE.db
anvi-get-sequences-for-hmm-hits -c $OUTPUT/contigs.db -p $OUTPUT/SAMPLES-MERGED-rerun2/PROFILE.db -C CONCOCT -o $OUTPUT/sequences-for-hmm-hits.tsv
anvi-get-sequences-for-hmm-hits -c $OUTPUT/contigs.db -o $OUTPUT/sequences-for-hmm-hits.tsv
#####
anvi-export-functions -c $OUTPUT/contigs.db -o $OUTPUT/COG_annotations.tsv --annotation-sources COG_FUNCTION,COG_CATEGORY
anvi-export-functions -c $OUTPUT/contigs.db --list-annotation-sources
anvi-export-functions -c /global/scratch/hpc3565/output_anvio5_1/contigs_db_versions/contigs_refined.db --list-annotation-sources
anvi-export-splits-taxonomy -c $OUTPUT/contigs.db -o $OUTPUT/splits-taxonomy-contigs-db.tsv



#### things to try 
anvi-search-functions
anvi-script-gen-CPR-classifier
anvi-script-predict-CPR-genomes



# Do the follow every so often 
anvi-export-collection -p $OUTPUT/SAMPLES-MERGED-taxa/PROFILE.db -C CONCOCT -O concoct_collection --include-unbinned 
anvi-export-splits-and-coverages -p $OUTPUT/SAMPLES-MERGED-taxa/PROFILE.db -c $OUTPUT/contigs.db -O $OUTPUT/splits-and-coverages.txt
anvi-export-splits-and-coverages -p $OUTPUT/SAMPLES-MERGED-concoct/PROFILE.db -c $OUTPUT/contigs.db -O $OUTPUT/splits-and-coverages.txt --report-contigs
anvi-export-contigs -c $OUTPUT/contigs.db --output-file $OUTPUT/contigs_backup
anvi-export-state -p $OUTPUT/SAMPLES-MERGED-taxa/PROFILE.db -o $OUTPUT/SAMPLES-MERGED-taxa-profile-db-state -s refining

cp -r $OUTPUT/contigs.db $BACKUP/contigs.db
cp -r $OUTPUT/SAMPLES-MERGED $BACKUP/SAMPLES-MERGED
cp -r -i $OUTPUT/SAMPLES-SUMMARY $BACKUP/SAMPLES-SUMMARY
cd /Users/grahamcolby/Documents/
sleep 40m ; tar -cjvf anvio_refining_2.tar.bz2 /Users/grahamcolby/Documents/anvio_refining

anvi-export-state -p $OUTPUT/sample_merge_summary_versions/SAMPLES-MERGED/PROFILE.db --list-states






